site_name: ISO TC 204 Ontologies
site_description: A registry for documenting the ontologies defined by TC 204
repo_url: https://github.com/ISO-TC204/ritso

nav:
  - TC204 on ISO.org: https://www.iso.org/committee/54706.html
  - TC204 Home: https://isotc204.org/
  - RITSO:
    - Home: index.md
    - Ontology formats: ontology_formats.md
    - Naming conventions: naming_conventions.md
    - Turtle file format: turtle.md
    - Ontology registry: ontology_registry.md
    - Concept registry: concept_registry.md
    - Imported ontologies:
      - foaf: https://isotc204.org/ontology-import-foaf
      - geo: https://isotc204.org/ontology-import-geo
      - gr: https://isotc204.org/ontology-import-gr
      - i72: https://isotc204.org/ontology-i72-v1
      - org: https://isotc204.org/ontology-import-org
      - prov: https://isotc204.org/ontology-import-prov
      - schema: https://isotc204.org/ontology-import-schema
      - time: https://isotc204.org/ontology-import-time
      - wgs84: https://isotc204.org/ontology-import-wgs84
      - xsd: https://isotc204.org/ontology-import-xsd
    - City Data Model:
      - Part 1: https://isotc204.org/ontology-cdm-p1-v1
      - Part 2: https://isotc204.org/ontology-cdm-p2-v1
      - Part 3: https://isotc204.org/ontology-cdm-p3-v1
    - ITS:
      - Core: https://isotc204.org/ontology-its-core-v1
      - Agent: https://isotc204.org/ontology-its-agent-v1
      - Location: https://isotc204.org/ontology-its-location-v1
      - Regulation: https://isotc204.org/ontology-its-regulation-v1
      - Time: https://isotc204.org/ontology-its-time-v1
      - Transport Network: https://isotc204.org/ontology-its-transport-network-v1
      - Vehicle: https://isotc204.org/ontology-its-vehicle-v1
site_url: https://isotc204.org/ritso/
use_directory_urls: true
copyright: <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"> <a href="https://creativecommons.org/licenses/by/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""></a></p>
theme:
  name: material
  features:
    - content.code.copy
    - content.status
    - content.tooltips
    - icons
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
  icon:
    repo: fontawesome/brands/github
    admonition:
      question: fontawesome/solid/comments
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
plugins:
  - search
  - git-revision-date-localized:
      type: date
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - meta
  - footnotes
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: docs
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
extra:
  search:
    highlight: true
  hide:
    - title
